DELETE http://localhost:8080/api/v1/pizzas/100
Accept: */*
Cache-Control: no-cache

<> 2019-01-28T083839.200.json
<> 2019-01-28T083740.200.json

###
#DELETE http://localhost:8080/api/v1/pizzas/100
#
#HTTP/1.1 404 Not Found
#Content-Type: text/plain
#Content-Length: 15
#
#Pizza not found
#
#Response code: 404 (Not Found); Time: 70ms; Content length: 15 bytes

